# Generated by Django 5.0.6 on 2024-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='codigo',
            field=models.FileField(upload_to=''),
        ),
    ]
