# Generated by Django 5.0.6 on 2024-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0002_alter_reporte_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='codigo',
            field=models.TextField(),
        ),
    ]
