# Generated by Django 5.0.6 on 2024-08-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analizador", "0004_alter_reporte_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporte",
            name="fileName",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
