# Generated by Django 5.0.6 on 2024-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analizador", "0005_reporte_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="fileName",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
