# Generated by Django 5.0.6 on 2024-12-15 01:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0006_alter_reporte_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='analysisTime',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
